.terraform_base:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
    - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/web_identity_token
    - cd terraform/hub
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}"

stages:
  - plan
  - apply

terraform-plan:
  extends: .terraform_base
  stage: plan
  script:
    - terraform plan -out=tfplan

terraform-apply:
  extends: .terraform_base
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform-plan
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success
    - when: never
