stages:
  - lint
  - validate
  - plan
  - apply

.terraform_base:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  variables:
    AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/web_identity_token
  before_script:
    - echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
    - cd terraform/${TF_ROOT}/environments/${ENV}
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}"

tflint:
  stage: lint
  image:
    name: ghcr.io/terraform-linters/tflint:latest
    entrypoint: [""]
  parallel:
    matrix:
      - ENV: [staging, prod]
  environment:
    name: ${ENV}
  script:
    - cd terraform/vpc-infra/environments/${ENV}
    - tflint --init
    - tflint --recursive --format=compact

tf_validate:
  extends: .terraform_base
  variables:
    TF_ROOT: "vpc-infra"
  stage: validate
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  parallel:
    matrix:
      - ENV: [staging, prod]
  environment:
    name: ${ENV}
  script:
    - terraform validate

tf_plan:
  extends: .terraform_base
  variables:
    TF_ROOT: "vpc-infra"
  stage: plan
  parallel:
    matrix:
      - ENV: [staging, prod]
  environment:
    name: ${ENV}
  script:
    - terraform plan -out=${ENV}.tfplan
  artifacts:
    paths:
      - terraform/vpc-infra/environments/${ENV}/${ENV}.tfplan

tf_apply:
  extends: .terraform_base
  variables:
    TF_ROOT: "vpc-infra"
  stage: apply
  parallel:
    matrix:
      - ENV: [staging, prod]
  environment:
    name: ${ENV}
  script:
    - terraform apply -auto-approve ${ENV}.tfplan
  rules:
    # Allow manual apply on the Merge Request to verify
    - if: $ENV == "staging" && $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    # Automatically keep main updated after merge
    - if: $ENV == "staging" && $CI_COMMIT_BRANCH == "main"
      when: on_success
    # ALWAYS manual for prod
    - if: $ENV == "prod" && $CI_COMMIT_BRANCH == "main"
      when: manual
