include:
  - local: .gitlab-ci/terraform.yml

variables:
  TF_ROOT: "vpc-infra"

tflint_vpc-infra:
  extends: .tflint_base
  script:
    - cd terraform/${TF_ROOT}/environments/${ENV}
    - tflint --init
    - tflint --recursive --format=compact

tf_validate_vpc-infra:
  extends: .tf_validate

tf_plan_vpc-infra:
  extends: .tf_plan

staging_apply_vpc-infra:
  extends: .staging_apply

prod_apply_vpc-infra:
  extends: .prod_apply
