stages:
  - lint
  - validate
  - plan
  - apply

.terraform_base:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  variables:
    AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/web_identity_token
    TF_VAR_aws_role_arn: $AWS_ROLE_ARN
  before_script:
    - echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
    - cd terraform/${TF_ROOT}/environments/${ENV}
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}"

.tflint_base:
  stage: lint
  image:
    name: ghcr.io/terraform-linters/tflint:latest
    entrypoint: [""]
  parallel:
    matrix:
      - ENV: [staging, prod]
  environment:
    name: ${ENV}

.tf_validate:
  extends: .terraform_base
  stage: validate
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  parallel:
    matrix:
      - ENV: [staging, prod]
  environment:
    name: ${ENV}
  script:
    - terraform validate

.tf_plan:
  extends: .terraform_base
  stage: plan
  parallel:
    matrix:
      - ENV: [staging, prod]
  environment:
    name: ${ENV}
  script:
    - terraform plan -out=${ENV}.tfplan
  artifacts:
    paths:
      - terraform/${TF_ROOT}/environments/${ENV}/${ENV}.tfplan
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" || $CI_MERGE_REQUEST_IID
      when: on_success

.staging_apply:
  extends: .terraform_base
  variables:
    ENV: "staging"
  stage: apply
  environment:
    name: staging
  script:
    - terraform apply -auto-approve staging.tfplan
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: manual
    - if: $CI_COMMIT_BRANCH == "main"
      when: on_success

.prod_apply:
  extends: .terraform_base
  variables:
    ENV: "prod"
  stage: apply
  environment:
    name: prod
  script:
    - terraform apply -auto-approve prod.tfplan
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
