apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fetchlabs-scanner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ehermenau/edge-first-infra.git
    targetRevision: main
    path: gitops/hub/apps/10-scanner/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: scanner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
