include:
  - local: "terraform/vpc-infra/.github/workflows.yml"

tf_plan_eks:
  extends: .terraform_base
  variables:
    TF_ROOT: "eks-infra"
  stage: plan
  parallel:
    matrix:
      - ENV: [staging]
  script:
    - terraform plan -out=${ENV}.tfplan
  artifacts:
    paths:
      - terraform/eks-infra/environments/${ENV}/${ENV}.tfplan
