name: Infra Workflow

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      workflow: ${{ steps.filter.outputs.workflow }}
      vpc: ${{ steps.filter.outputs.vpc }}
      eks: ${{ steps.filter.outputs.eks }}
    steps:
      - uses: actions/checkout@v4 
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: | 
            workflow:
              - '.github/workflows/workflow.yml'
              - '.github/workflows/**/*'
            vpc:
              - 'terraform/vpc-infra/**/*'
            eks:
              - 'terraform/eks-infra/**/*'

  tf_lint_validate:
    needs: changes
    strategy:
      matrix:
        BASE: [vpc-infra, eks-infra]
    if: |
      needs.changes.outputs.workflow == 'true' ||
      needs.changes.outputs.vpc == 'true' ||
      needs.changes.outputs.eks == 'true' ||
      github.ref == '/refs/heads/main'
    uses: ./.github/workflows/tf_lint_validate.yml
    with:
      TF_ROOT: terraform/${{ matrix.BASE }}

  vpc_staging_tf_plan_apply:
    needs: [changes, tf_lint_validate]
    if: | 
      needs.changes.outputs.workflow == 'true' ||
      needs.changes.outputs.vpc == 'true'
    uses: ./.github/workflows/tf_plan_apply.yml
    with:
      TF_ROOT: terraform/vpc-infra
      ENV: staging

  vpc_prod_tf_plan_apply:
    needs: [changes, tf_lint_validate]
    if: | 
      (needs.changes.outputs.workflow == 'true' || needs.changes.outputs.vpc == 'true') &&
      github.ref == '/refs/heads/main'
    uses: ./.github/workflows/tf_plan_apply.yml
    with:
      TF_ROOT: terraform/vpc-infra
      ENV: prod 

  eks_staging_tf_plan_apply:
    needs: [changes, tf_lint_validate, vpc_staging_tf_plan_apply]
    if: | 
      needs.changes.outputs.workflow == 'true' ||
      needs.changes.outputs.eks == 'true'
    uses: ./.github/workflows/tf_plan_apply.yml
    with:
      TF_ROOT: terraform/eks-infra
      ENV: staging

  eks_prod_tf_plan_apply:
    needs: [changes, tf_lint_validate]
    if: | 
      (needs.changes.outputs.workflow == 'true' || needs.changes.outputs.eks == 'true') &&
      github.ref == '/refs/heads/main'
    uses: ./.github/workflows/tf_plan_apply.yml
    with:
      TF_ROOT: terraform/eks-infra
      ENV: prod 
